### PR TITLE
Use depends_on so that wordpress doesn't have to wait for the db

### PR DESCRIPTION
**Pull request by HackToHell**
Also removed the IP so that it's generic and binds to 0.0.0.0
Also removed the network as the docker compose v2 does that by default.

### CODE REVIEW

**Comment by nezhar** [comment]
The _depends_on_ option should be added, I totally agree.

As for the network, an explicit definition makes it easier to understand what is going on there, and how the services connect to each other. This might be useful when adding other services.

The IP address configuration is important, at least kind of a hint on how to set it, so you can run multiple development environments on the same machine without conflicting ports.

**Comment by HackToHell** [comment]
Ah okay, let me add in the docs on the IP @nezhar and set it to 127.0.0.1, because that's the default for most people, and they might not realise why it isn't working. I'll also push back the networks.

**Comment by nezhar** [comment]
I agree with that. Please update the pull request so I can merge.

**Comment by HackToHell** [comment]
Done :+1:

**Comment by pdostal** [comment]
Why do you specify the IP address? It listens on `0.0.0.0` by default which should be fine almost every development environment.

**Comment by nezhar** [comment]
@pdostal the idea is to use an explicit configuration. This is helpful if you need more than one instance of this configuration to run on the same machine.

**Pull request merged**
