### PR TITLE
Set apache run as current user

### PR DESCRIPTION
**Pull request by theandersonn**
I was having trouble running WordPress with recommended permissions for folders and files. I got it through the following setup.

### CODE REVIEW

**Comment by theandersonn** [comment]
https://github.com/nezhar/wordpress-docker-compose/issues/28

**Comment by nezhar** [comment]
This is not bad and i think it could help solving the permission issue. The Wordpress container is based on the PHP docker container, which has documented this behavior (https://hub.docker.com/_/php/ - Running as an arbitrary user)

I will although add this to the readme, as this is something each developer should configure if required :slightly_smiling_face:

**Comment by theandersonn** [comment]
This alternative was inconsistent.
When starting the container, the user and group has problems with the user and group of the volume.

I am using user www-data and put it in my logged in user group.

Example: www-data: $ USER

I believe that this treatment would be ideal:
https://github.com/nezhar/laravel-docker-compose/blob/master/docker/php/entrypoint

How to apply this implementation to this project?

**Comment by nezhar** [comment]
I was thinking for a while to add this also in this repository, but this will change a bit the structure and the docs must be adapted.

I may combine this with the already existing branch for https: https://github.com/nezhar/wordpress-docker-compose/tree/https

**Comment by theandersonn** [comment]
I understood. In my opinion, even if the folder organization changes slightly, the benefit of having the paired permissions will be greater.
Because for those unaware, you have to set 777 permission to run WordPress correctly.

**Comment by palomnik** [comment]
I've been running a script to change ownership back and forth between www-data and the local user (I sync the files in dropbox).  This works but is extra hassle.

I discovered this solution which uses a host volume instead of the default wp-app local volume.

https://kaspars.net/blog/docker-volume-permissions

Thoughts?

**Pull request closed without merging**
