### PR TITLE
Added links to allow db accessible in wordpress container.

### PR DESCRIPTION
**Pull request by Aeyzaz**

### CODE REVIEW

**Comment by slhck** [comment]
Is this really necessary? WordPress can be installed without this link, so apparently the container already has access to the database.

**Comment by Aeyzaz** [comment]
I have hosted multiple docker containers and connected them to two separate domains using nginx proxy server and i was not able to access the database in wordpress service. after adding link to db i was able to access the db service in wordpress container. Although a simple change but it can save someones' time.

**Comment by nezhar** [comment]
@Aeyzaz Thanks for your input.

According to the docker-compose docs this isn't really necessary as the containers get linked by default: https://docs.docker.com/compose/compose-file/#links

The MySQL service takes a bit longer to start on creation and the WordPress container cannot reach the database as it is still in setup. At some point the WordPress container may stop and you have to stop and start the containers. Can this be related to your issue?

Having links in the docker-compose.yml makes it a bit more verbose. But I have to agree, if it can solve such issues it is better to add it instead of wasting time :slightly_smiling_face:

**Comment by Aeyzaz** [comment]
No, as the yml file already has depends_on parameter set up the container still wasn't able tp access mysql service by adding link it solved the issue.

**Pull request merged**
